#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCMathFoundation-import-private.h
src/reflect/_MulleObjCMathFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCMathFoundation-import.h
src/reflect/_MulleObjCMathFoundation-include.h
)

set( PUBLIC_HEADERS
src/MulleObjCLoader+MulleObjCMathFoundation.h
src/MulleObjCMathFoundation.h
src/import.h
)

