# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: D8EEFBC1-C5F7-434D-881E-F5D620BC0B21;math;no-all-load,no-build,no-cmake-inherit,no-delete,no-dependency,no-fs,no-import,no-platform-windows,no-require,no-share,no-update;m
# Disable with : `mulle-sourcetree mark math `
# Disable for this platform: `mulle-sourcetree mark math no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark math no-cmake-sdk-<name>`
#
if( NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( COLLECT_OS_SPECIFIC_LIBRARIES_AS_NAMES)
      list( APPEND OS_SPECIFIC_LIBRARIES "m")
   else()
      if( NOT MATH_LIBRARY)
         find_library( MATH_LIBRARY NAMES
            m
         )
         message( STATUS "MATH_LIBRARY is ${MATH_LIBRARY}")
         #
         # The order looks ascending, but due to the way this file is read
         # it ends up being descending, which is what we need.
         #
         if( MATH_LIBRARY)
            #
            # Add MATH_LIBRARY to OS_SPECIFIC_LIBRARIES list.
            # Disable with: `mulle-sourcetree mark math no-cmake-add`
            #
            list( APPEND OS_SPECIFIC_LIBRARIES ${MATH_LIBRARY})
            # intentionally left blank
         else()
            # Enable with: `mulle-sourcetree mark math require`
            message( STATUS "MATH_LIBRARY is missing but it is marked as \"no-require\"")
         endif()
      endif()
   endif()
endif()
