/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_math_foundation_include_h__
#define _mulle_objc_math_foundation_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove math`
// (Use D8EEFBC1-C5F7-434D-881E-F5D620BC0B21 instead of math, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark math no-header`
//    rename              : `mulle-sde dependency|library set math include whatever.h`
//    reorder             : `mulle-sde dependency move math <up|down>`
//    toggle #include: `mulle-sde dependency mark math [no-]import`
//    toggle public       : `mulle-sde dependency mark math [no-]public`
//    toggle optional     : `mulle-sde dependency mark math [no-]require`
//    remove for platform : `mulle-sde dependency mark math no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if ! defined( _WIN32)
# ifdef __has_include
#  if __has_include(<math.h>)
#    include <math.h>   // math
#   define HAVE_LIB_MATH
#  endif
# endif
#endif

#endif
