/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjCMathFoundation_include_h__
#define _MulleObjCMathFoundation_include_h__

// How to tweak the following math #include
//    remove:             `mulle-sourcetree mark math no-header`
//    rename:             `mulle-sde dependency|library set math include whatever.h`
//    toggle #import:     `mulle-sourcetree mark math [no-]import`
//    toggle localheader: `mulle-sourcetree mark math [no-]localheader`
//    toggle public:      `mulle-sourcetree mark math [no-]public`
//    toggle optional:    `mulle-sourcetree mark math [no-]require`
//    remove for os:      `mulle-sourcetree mark math no-os-<osname>`
# if defined( __has_include) && __has_include("math.h")
#   include "math.h"   // math
# else
#   include <math.h>   // math
# endif

#endif
