/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_math_foundation_include_h__
#define _mulle_objc_math_foundation_include_h__

// You can tweak the following #include with these commands.
// (Use D8EEFBC1-C5F7-434D-881E-F5D620BC0B21 instead of math if there are duplicate entries)
//    remove:             `mulle-sourcetree mark math no-header`
//    rename:             `mulle-sde dependency|library set math include whatever.h`
//    reorder:            `mulle-sourcetree move math <up|down>`
//    toggle #include:    `mulle-sourcetree mark math [no-]import`
//    toggle public:      `mulle-sourcetree mark math [no-]public`
//    toggle optional:    `mulle-sourcetree mark math [no-]require`
//    remove for platform:`mulle-sourcetree mark math no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <math.h>   // math

#endif
