/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_math_foundation_include_h__
#define _mulle_objc_math_foundation_include_h__

// How to tweak the following math #include
//    remove:          `mulle-sourcetree mark math no-header`
//    rename:          `mulle-sourcetree mark math set include whatever.h`
//    toggle public:   `mulle-sourcetree mark math [no-]public`
//    toggle optional: `mulle-sourcetree mark math [no-]require`
//    remove for os:   `mulle-sourcetree mark math no-os-<osname>`
# include <math.h>   // math

#endif
